monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - chrome_php

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!chrome_php"]
            chrome_php:
                level:    debug
                type:     rotating_file
                max_files: 10
                path:     '%kernel.logs_dir%/%kernel.environment%_chrome_php.log'
                channels: [chrome_php]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event", "!chrome_php"]
            chrome_php:
                level:    debug
                type:     rotating_file
                max_files: 10
                path:     '%kernel.logs_dir%/%kernel.environment%_chrome_php.log'
                channels: [chrome_php]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
                channels: ["!chrome_php"]
            chrome_php:
                level:    debug
                type:     rotating_file
                max_files: 10
                path:     '%kernel.logs_dir%/%kernel.environment%_chrome_php.log'
                channels: [chrome_php]
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
